version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pacman
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"